name: Marindeck

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    exactVersion: 5.12.0
  MarkdownView:
    url: https://github.com/hirossan4049/MarkdownView
    revision: 753be391e6d3640161ca21f49a57c306aaebaf3a
  GiphyUISDK:
    url: https://github.com/Giphy/giphy-ios-sdk
    exactVersion: 2.1.16
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift.git
    exactVersion: 6.5.0
  RxWebKit:
    url: https://github.com/RxSwiftCommunity/RxWebKit
    exactVersion: 2.0.1

      

options:
  #bundleIdPrefix: marindeck
  postGenCommand: rbenv exec pod install
  developmentLanguage: en

settingGroups:
  MarindeckBaseSettings:
    SWIFT_OBJC_BRIDGING_HEADER: Marindeck/Marindeck-Bridging-Header.h

settings:
  base:
    DEVELOPMENT_TEAM: 726VR75V6L
    MARKETING_VERSION: 0.1.4
    CURRENT_PROJECT_VERSION: 0.1.4
  config:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"


targets:
  Marindeck:
    type: application
    platform: iOS
    deploymentTarget: "14.1"
    sources: Marindeck
    scheme: {}
    settings:
      base:
        DEVELOPMENT_TEAM: 726VR75V6L
        PRODUCT_BUNDLE_IDENTIFIER: marindeck
        DISPLAY_APPNAME: MarinDeck
    dependencies:
      - package: GRDB
      - package: MarkdownView
      - package: GiphyUISDK
      - package: RxWebKit
      - package: RxSwift
    preBuildScripts:
      - path: ./scripts/swiftlint.sh
        name: Run SwiftLint

  Marindeck-dev:
    type: application
    platform: iOS
    deploymentTarget: "14.1"
    sources: Marindeck
    scheme: {}
    settings:
      base:
        DEVELOPMENT_TEAM: 726VR75V6L
        PRODUCT_BUNDLE_IDENTIFIER: marindeck.dev
        DISPLAY_APPNAME: MD-dev
    dependencies:
      - package: GRDB
      - package: MarkdownView
      - package: GiphyUISDK
      - package: RxWebKit
      - package: RxSwift
