name: Marindeck

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    exactVersion: 5.12.0
  MarkdownView:
    url: https://github.com/hirossan4049/MarkdownView
    revision: 753be391e6d3640161ca21f49a57c306aaebaf3a
  GiphyUISDK:
    url: https://github.com/Giphy/giphy-ios-sdk
    exactVersion: 2.1.16
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift.git
    exactVersion: 6.5.0
  RxWebKit:
    url: https://github.com/RxSwiftCommunity/RxWebKit
    exactVersion: 2.0.1
  Loaf:
    url: https://github.com/schmidyy/Loaf
    exactVersion: 0.6.0

      

options:
  #bundleIdPrefix: marindeck
  postGenCommand: rbenv exec pod install
  developmentLanguage: en

settingGroups:
  MarindeckBaseSettings:
    SWIFT_OBJC_BRIDGING_HEADER: Marindeck/Marindeck-Bridging-Header.h

settings:
  base:
    DEVELOPMENT_TEAM: 726VR75V6L
    MARKETING_VERSION: 0.1.14
    CURRENT_PROJECT_VERSION: 0.1.14
  config:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

        # schemes:
        #   Debug:
        #     build:
        #     targets:
        #       MarinDeck: all
        #       MarinDeckTests: [test]
        # 
        #   Release:
        #     build:
        #     targets:
        #       MarinDeck: all
        #       MarinDeckTests: [test]
        # 
        #   run:
        #     config: Release
        #   test:
        #     config: Release
        #   profile:
        #     config: Release
        #   analyze:
        #     config: Release
        #   archive:
        #     config: Release



targets:
  Marindeck:
    type: application
    platform: iOS
    deploymentTarget: "14.1"
    sources: Marindeck
    scheme: {}
    settings:
      base:
        DEVELOPMENT_TEAM: 726VR75V6L
        PRODUCT_BUNDLE_IDENTIFIER: marindeck
        DISPLAY_APPNAME: MarinDeck
    dependencies:
      - package: GRDB
      - package: MarkdownView
      - package: GiphyUISDK
      - package: RxWebKit
      - package: RxSwift
      - package: Loaf
    preBuildScripts:
      - path: ./scripts/swiftlint.sh
        name: Run SwiftLint
      - path: ./scripts/vite.sh
        name: Build Vite

  Marindeck-dev:
    type: application
    platform: iOS
    deploymentTarget: "14.1"
    sources: Marindeck
    scheme: {}
    settings:
      base:
        DEVELOPMENT_TEAM: 726VR75V6L
        PRODUCT_BUNDLE_IDENTIFIER: marindeck.dev
        DISPLAY_APPNAME: MD-dev
    dependencies:
      - package: GRDB
      - package: MarkdownView
      - package: GiphyUISDK
      - package: RxWebKit
      - package: RxSwift
      - package: Loaf
